# Question 1

In [2]:
import numpy as np
# first method
arr = np.arange(start=2,stop=50, step=3)

In [3]:
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [4]:
# second method
arr1 = np.arange(2,50,3)

In [5]:
arr1

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2

In [24]:
# For list of integers 
lst1 = [] 

lst2 = [] 
lst3 = []


lst1 = [int(item) for item in input("Enter the list elements : ").split()] 

lst2 = [int(item) for item in input("Enter the list elements : ").split()] 
lst3 = sorted(lst1 + lst2)


print(lst1)  
print(lst2)
print(lst3)


Enter the list elements : 10 25 8 70 15
Enter the list elements : 60 10 80 32 14
[10, 25, 8, 70, 15]
[60, 10, 80, 32, 14]
[8, 10, 10, 14, 15, 25, 32, 60, 70, 80]


# Question 3

In [25]:
b = np.array([[2,10,7,4],[5,3,8,15],[20,2,41,9,15]])

/home/billo/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [26]:
print(b)

[list([2, 10, 7, 4]) list([5, 3, 8, 15]) list([20, 2, 41, 9, 15])]


In [27]:
print(type(b))

<class 'numpy.ndarray'>


In [28]:
print(b.dtype)

object


In [29]:
print(b.shape)

(3,)


In [57]:
arr = np.arange(20).reshape(4,5)

In [58]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
arr.shape

(4, 5)

In [60]:
y = np.expand_dims(arr, axis=0)

In [61]:
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [62]:
p = np.expand_dims(arr, axis=1)

In [63]:
p

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19]]])

# Question 5

In [65]:
m = np.array([5,10,2,9])
p = np.array([8,15,8,20])
print("first list:",m)
print("second list",p)

first list: [ 5 10  2  9]
second list [ 8 15  8 20]


In [70]:
result1 = np.hstack(m + p)
result2 = np.vstack(m + p)

In [72]:
result1


array([13, 25, 10, 29])

In [73]:
result2

array([[13],
       [25],
       [10],
       [29]])

In [74]:
print("horizontaly",result1)
print("vertically :",result2)

horizontaly [13 25 10 29]
vertically : [[13]
 [25]
 [10]
 [29]]


# Question 6

In [76]:
#Unique value

items = ['a','b','c','d','e','a','a','e','b','a','a','b','c','d','e','a','a','e','b','a','a','b','c','d','e','a','a','e','b','a',]

np.unique(items)

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [78]:
letters ="aaabbbbbcccccccdddddddccccyyyyrrrrrbbbbbbooooaaaaaawwwwwyyyiiiitttttggggkkkccvvzzxxssd"
td = dict(zip(list(letters),[list(letters).count(i) for i in list(letters)]))
print(td)

{'a': 9, 'b': 11, 'c': 13, 'd': 8, 'y': 7, 'r': 5, 'o': 4, 'w': 5, 'i': 4, 't': 5, 'g': 4, 'k': 3, 'v': 2, 'z': 2, 'x': 2, 's': 2}
